version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    ports:
      - "8080:8080"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "yarn start"